name: Deploy to EC2

on:
  push:
    branches:
      - main  # Se activa cuando haces push en la rama main.

jobs:
  deploy-gaby:
    runs-on: gabyrunner
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4  # Clona tu código en la maquinita de GitHub
    - name: copy env
      run: cp ~/.env . 
    - name: Install Dependencies
      run: npm install
    - name: Restart Server
      run: sudo pm2 restart all 

  deploy-andrew:
    runs-on: andrew
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4  # Clona tu código en la maquinita de GitHub
    - name: copy env
      run: cp ~/.env . 
    - name: Install Dependencies
      run: npm install
    - name: Restart Server
      run: sudo pm2 restart all 
  deploy-andresito:
    runs-on: andresito
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4  # Clona tu código en la maquinita de GitHub
    - name: copy env
      run: cp ~/.env . 
    - name: Install Dependencies
      run: npm install
    - name: Restart Server
      run: sudo pm2 restart all 
      





