name: CI/CD - Deploy to EC2

on:
  push:
    branches:
      - main
      - andresito
      - gaby
      - andrew
      - ali
      - luciana

jobs:
  # Producción de Andresito (push a main)
  deploy-andresito-prod:
    runs-on: andresito
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4   
      - name: copy env
        run: cp ~/.env . 
      - name: Install Dependencies
        run: npm install
      - name: Restart Server
        run: pm2 restart udp
      - name: Retsart another server
        run: pm2 restart web
      - name: PM2 Status
        run: pm2 list 

  # Test de Andresito (push a andresito)
  deploy-andresito-test:
    runs-on: andresito
    if: github.ref == 'refs/heads/andresito'
    steps:
      - name: Deploy andresito branch to testsito folder
        run: |
          cd /home/ubuntu/testsito
          git pull origin andresito
          npm install
          pm2 restart andresitoweb
          pm2 restart andresitoudp
          pm2 list

  # Producción de Gaby (push a main)
  deploy-gaby-prod:
    runs-on: gaby
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4   
      - name: copy env
        run: cp ~/.env . 
      - name: Install Dependencies
        run: npm install
      - name: Restart Server
        run: pm2 restart udp
      - name: Retsart another server
        run: pm2 restart web
      - name: PM2 Status
        run: pm2 list 

  # Test de Gaby (push a gaby)
  deploy-gaby-test:
    runs-on: gaby
    if: github.ref == 'refs/heads/gaby'
    steps:
      - name: Deploy andresito branch to testsito folder
        run: |
          cd /home/ubuntu/gabtest/P1_S4_UDP-WEB_SERVER
          git pull origin gaby
          npm install
          pm2 restart gaby_web_test
          pm2 restart gaby_udp_test
          pm2 list

  # Producción de Andrew (push a main)
  deploy-andrew-prod:
    runs-on: andrew
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4   
      - name: copy env
        run: cp ~/.env . 
      - name: Install Dependencies
        run: npm install
      - name: Restart Server
        run: pm2 restart udp_server
      - name: Retsart another server
        run: pm2 restart web_server
      - name: PM2 Status
        run: pm2 list 

  # Test de Andrew (push a andrew)
  deploy-andrew-test:
    runs-on: andrew
    if: github.ref == 'refs/heads/andrew'
    steps:
      - name: Deploy andresito branch to testsito folder
        run: |
          cd /home/ubuntu/andrew_test/P1_S4_UDP-WEB_SERVER
          git pull origin andrew
          npm install
          pm2 restart web_test
          pm2 restart udp_test
          pm2 list

  # Producción de Ali (push a main)
  deploy-ali-prod:
    runs-on: ali-runner
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: copy env
        run: cp ~/.env . 
      - name: Install Dependencies
        run: npm install
      - name: Restart Server
        run: sudo pm2 restart all

  # Test de Ali (push a ali)
  deploy-ali-test:
    runs-on: ali-runner
    if: github.ref == 'refs/heads/ali'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: copy env
        run: cp ~/.env . 
      - name: Install Dependencies
        run: npm install
      - name: Restart Server
        run: sudo pm2 restart all 
      - name: PM2 Status
        run: sudo pm2 list
        
  # Producción de Luciana (push a main)
  deploy-lucy-prod:
    runs-on: lucy-runner
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: copy env
        run: cp ~/.env . 
      - name: Install Dependencies
        run: npm install
      - name: Restart Server
        run: sudo pm2 restart all

  # Test de Lucy (push a luciana)
  deploy-lucy-test:
    runs-on: lucy-runner
    if: github.ref == 'refs/heads/luciana'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: copy env
        run: cp ~/.env . 
      - name: Install Dependencies
        run: npm install
      - name: Restart Server
        run: sudo pm2 restart all 
      - name: PM2 Status
        run: sudo pm2 list
