name: CI/CD - Deploy to EC2

on:
  push:
    branches:
      - main
      - andresito
      - gaby
      - andrew
      

jobs:
  # Producción de Andresito (push a main)
  deploy-andresito-prod:
    runs-on: andresito
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4   
      - name: Install Dependencies
        run: npm install
      - name: Restart Server
        run: pm2 restart web
      - name: PM2 Status
        run: pm2 list 

  # Test de Andresito (push a andresito)
  deploy-andresito-test:
    runs-on: andresito
    if: github.ref == 'refs/heads/andresito'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      - name: Restart Andresito Test Server
        run: pm2 restart andresitoweb
      - name: PM2 Status
        run: pm2 list

  # Producción de Gaby (push a main)
  deploy-gaby-prod:
    runs-on: gaby
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4  
      - name: Install Dependencies
        run: npm install
      - name: Restart Server
        run: sudo pm2 restart all 
      - name: PM2 Status
        run: sudo pm2 list
  # Test de Gaby (push a gaby)
  deploy-gaby-test:
    runs-on: gaby
    if: github.ref == 'refs/heads/gaby'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      - name: Restart Gaby Test Server
        run: sudo pm2 restart all 
      - name: PM2 Status
        run: sudo pm2 list

  # Producción de Andrew (push a main)
  deploy-andrew-prod:
    runs-on: andrew
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4  
      - name: Install Dependencies
        run: npm install
      - name: Restart Server
        run: sudo pm2 restart all
      - name: PM2 Status
        run: sudo pm2 list 

  # Test de Andrew (push a andrew)
  deploy-andrew-test:
    runs-on: andrew
    if: github.ref == 'refs/heads/andrew'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      - name: Restart Andrew Test Server
        run: sudo pm2 restart all 
      - name: PM2 Status
        run: sudo pm2 list
